name: shrine_portal
description: A fashionable retail app.
version: 2023.03.18+1756

environment:
  sdk: '>=2.18.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  animations: ^2.0.7
  collection: ^1.17.1
  flutter_staggered_grid_view: ^0.6.2
  shared_preferences: ^2.1.1
  cupertino_icons: ^1.0.2
  rxdart: ^0.27.7
  google_fonts: ^4.0.3
  provider: ^6.0.5
  dio: ^5.1.2
  go_router: ^7.0.1
  flutter_adaptive_scaffold: ^0.1.3
  flukit: ^3.0.1
  easy_refresh: ^3.3.1+2
  json_annotation: ^4.8.1
  get_it: ^7.6.0
  fluttertoast: ^8.2.1
  #  levir:
  #    git:
  #      url: https://github.com/shrinex/levir.git
  #      ref: main
  levir:
    path: ../levir

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  build_runner: ^2.4.0
  mockito: ^5.4.0
  json_serializable: ^6.6.0

flutter:
  uses-material-design: true